### ISSUE TITLE
建议 添加限制 dnsmasq.log 日志文件大小，不然时间久了会占用大量磁盘空间

### ISSUE THREAD

**Issue by able8** [elespejo/dnsmasq#1]
我有台vps开启dnsmsq日志，后来发现dnsmasq.log占用7G磁盘空间。

docker compose 设置 log 大小官方说明：
The default driver json-file, has options to limit the amount of logs stored. To do this, use a key-value pair for maximum storage size and maximum number of files:
```
options:
  max-size: "200k"
  max-file: "10"
```
The example shown above would store log files until they reach a max-size of 200kB, and then rotate them. The amount of individual log files stored is specified by the max-file value. As logs grow beyond the max limits, older log files are removed to allow storage of new logs.

Here is an example docker-compose.yml file that limits logging storage:
```
services:
  some-service:
    image: some-service
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```
